apiVersion: v1
kind: ConfigMap
metadata:
  name: jobtracker-config
data:
  db-host: "postgres-service"
  db-name: "jobtracker"
  redis-addr: "redis-service:6379"
  server-port: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: jobtracker-secrets
type: Opaque
data:
  db-password: dld6TDJXeUhDdThZOXg3NWFpM3VRckJVNjh6cDZGOGs=
  jwt-secret: NmRxc01yRG5kakFCRXY0VjllSFRZcmtOckNxM2o5ektiQ3NmUVhidUdVNHc0Nldq
